<section class="mt-9 mb-5 p-4">
  <div class="container d-flex flex-wrap mt-2 mb-2 p-2">
    <div class="w-100 d-flex flex-wrap mt-2 mb-2 p-2">
      <h2 class="d-flex m-auto text-md text-center text-color-1 font-weight-bold">Términos y Condiciones</h2>
    </div>
    <div class="w-100 d-flex flex-wrap mt-2 mb-2 p-2">
      <h2 class="d-flex m-auto text-md text-center text-color-1 font-weight-normal">VIVÉ SUMINISTROS MÉDICOS</h2>
    </div>
    <div class="w-100 d-flex flex-wrap mt-2 mb-2 p-2">
      <p class="d-flex mt-2 mb-2 text-md text-justify text-color-1 font-weight-light">Es requisito necesario para proporcionar los servicios y/o productos que se ofrecen en este sitio, que lea y acepte los siguientes Términos y Condiciones que a continuación se redactan.</p>
      <p class="d-flex mt-2 mb-3 text-md text-justify text-color-1 font-weight-light x">El uso de nuestros servicios y/o productos así como la compra de estos, implicará que usted ha leído y aceptado los Términos y Condiciones de Uso en el presente documento. En algunos casos, para adquirir un servicio y/o producto, será necesario el registro por parte del usuario, con ingreso de datos personales fidedignos y definición de una contraseña.</p>
      <p class="d-flex mt-2 mb-3 text-md text-justify text-color-1 font-weight-light x">El usuario puede elegir y cambiar la clave para su acceso de administración de la cuenta en cualquier momento, en caso de que se haya registrado y que sea necesario para la compra de alguno de nuestros servicios y/o productos VIVÉ SUMINISTROS MÉDICOS no asume la responsabilidad en caso de que entregue dicha clave a terceros.</p>
      <p class="d-flex mt-2 mb-3 text-md text-justify text-color-1 font-weight-light x">Toda la información contenida en VIVÉ SUMINISTROS MÉDICOS y www.vivesm.com es provista para uso informativo y no da ninguna garantía de ningún tipo, a excepción de cuando se exprese abiertamente. VIVÉ SUMINISTROS MÉDICOS se esfuerza en proporcionar información exacta y actualizada dentro de nuestro sitio web. De cualquier forma, VIVÉ SUMINISTROS MÉDICOS no representa o garantiza la disponibilidad, exactitud o la integridad de cualquier información contenida aquí y expresamente renuncia a cualquier obligación de actualizar dicha información. (NOMBRE DE LA EMPRESA) no asume responsabilidad alguna de cualquier error u omisión dentro del sitio web.</p>
      <p class="d-flex mt-2 mb-3 text-md text-justify text-color-1 font-weight-light x">Todas las compras y transacciones que se lleven a cabo por medio de este sitio web, están sujetas a un proceso de confirmación y verificación, el cual podría incluir la verificación de agenda y disponibilidad, validación de la forma de pago, validación de la factura (en caso de existir) y el cumplimiento de las condiciones requeridas por el medio de pago seleccionado. En algunos casos puede que se requiera una verificación por medio de correo electrónico.</p>
       <p class="d-flex mt-2 mb-3 text-md text-justify text-color-1 font-weight-light x">Puede usted sentirse libre de navegar el sitio y descargar información para su uso personal y no para uso comercial. Todos los derechos reservados e información protegida por los derechos de autor contenidos en los materiales de descarga deben ser retenidas. Usted debe asumir que toda la información publicada en nuestro sitio web está protegida por los derechos de autor a menos que se indique lo contrario, el uso de dicha información debe ser como se indica aquí y con el permiso expresado por escrito por parte de VIVÉ SUMINISTROS MÉDICOS.</p>
      <p class="d-flex mt-2 mb-3 text-md text-justify text-color-1 font-weight-light x">Le está prohibido alterar, dañar o desfigurar el sitio web o agregar cualquier material no autorizado al sitio web. Es de su conocimiento que VIVÉ SUMINISTROS MÉDICOS protegerá de manera recia el sitio web.</p>
      <p class="d-flex mt-2 mb-3 text-md text-justify text-color-1 font-weight-light x">VIVÉ SUMINISTROS MÉDICOS se reserva el derecho de alterar o borrar material del sitio web en cualquier momento, sin previo aviso y puede en todo momento revisar los Términos y Condiciones y otras políticas aplicables para este sitio web actualizando esta publicación. Usted está obligado por tales revisiones y debería, por lo tanto, visitar periódicamente esta página para revisar los Términos, Condiciones y Políticas vigentes a ese momento.</p>
    </div>
  </div>
</section>